version: '3.3'

services:
    database:
        build:
            context: ./database
            dockerfile: Dockerfile
        restart: "always"
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: discordBot
            POSTGRES_PASSWORD: password123
            POSTGRES_DB: polytopiaHelper_dev
        #env_file:
        #    - .env
        volumes:
            # - ./database/1_init_sql.sql:/docker-entrypoint-initdb.d/1_init.sql
            - ./db-data/:/var/lib/postgresql/data/

    helper:
        build:
            context: "/Users/jean/Documents/Coding/Polytopia/src/"
            dockerfile: Dockerfile
        restart: "always"
        volumes:
            - /Users/jean/Documents/Coding/Polytopia/src:/app
        env_file:
            - .env
        depends_on:
            - database

    jupyter-notebook:
        image: jupyter/datascience-notebook
        environment:
            - CHOWN_HOME=yes
            - CHOWN_HOME_OPTS='-R'
        volumes:
            - /Users/jean/Documents/Coding/Polytopia/jupyter_noteboooks:/home/jovyan/work
        ports:
            - 8888:8888
